### ISSUE TITLE
No WebSocket connection URL specified in connect method

### ISSUE THREAD

**Issue by fsamir** [DataTorrent/malhar-angular-dashboard#122]
Hi folks,

first of all, thanks for providing such a nice tool.

This is probably not a bug, just user error. However, I couldn't find a mail list to post the question, so I am posting it here. Please let me know if this is not the appropriated place.

I am trying to customise the line chart to feed from a datamodel that subscribes to a websocket. My DataModel is a copy of `WebSocketWidgetDataModel` and when I run the app I get the error below:

```
TypeError: No WebSocket connection URL specified in connect method
    at Object.$get.webSocketService.connect (http://localhost:3000/lib/malhar-angular-widgets/dist/malhar-angular-widgets.js:691:23)
```

Where am I supposed to call  `webSocket.setWebSocketURL(settings.webSocketURL);` ?

Thanks

**Comment by andyperlitch** [comment]
Hey @fsamir,

That error comes from [this webSocket service](https://github.com/DataTorrent/malhar-angular-widgets/blob/master/src/service/websocket.js), which assumes a websocket server back-end that supports a particular websocket message schema:

```js
{
   "topic": "{topic_name}",
   "type": "{subscribe|publish|unsubscribe}",
   "data": {
      /* arbitrary data */
   }
}
```

The error you are seeing is because you have not specified a URL to connect to this server. The `setWebSocketURL` method is actually on the **webSocketProvider**, which needs to be called in a config block, a la:

```js
angular.module('app', [])
.config(settings, webSocketProvider) {
   webSocketProvider.setWebSocketURL(settings.webSocketURL);
}
```

Sorry for the confusion, I hope this helps!

-Andy

**Comment by fsamir** [comment]
Thanks Andy.
