### ISSUE TITLE
Setting scope on widget directives

### ISSUE THREAD

**Issue by spiermar** [DataTorrent/malhar-angular-dashboard#127]
Following the examples, I have something like this:

```
directives.directive('lineTimeSeries', function (D3Service) {
    return {
        restrict: 'A',
        replace: true,
        templateUrl: 'partials/line-timeseries.html',
        scope: {
            data: '='
        },
        link: function (scope) {
            scope.yAxisTickFormat = D3Service.yAxisTickFormat;
            scope.xAxisTickFormat = D3Service.xAxisTickFormat;
            scope.yFunction = D3Service.yFunction;
            scope.xFunction = D3Service.xFunction;
        }
    };
});
```

I need to set the data variable so the data model can "talk" with this directive, and the way it's working right now:

```
scope: {
    data: '='
}
```

The scope is completely replaced, loosing inheritance and consequently, the ability to use parent's properties.

I've tried to set the data parameter in the "link" function:

```
link: function (scope) {
    scope.data = '=';
}
```

But no luck. The data model could not update the "data" variable.

Is there any way to create the widget scope without breaking inheritance?

Cheers,
Martin

**Comment by awashbrook** [comment]
Isolated scopes allow us create reusable widgets. This can be a difficult trade off as coding portable directives tends to involve a substantially greater investment of time up front: you should identify any component you may want others to leverage outside your angular application up front, and invest the time in designing your app to support that; you will find it very difficult to back afterward and refactor those widgets that others want to embed!

The malhar dashboard is is fostering a dashboard of portable widgets, providing separation of concerns betweens data model and directives, loosely couple together the `data` attribute (best practice as per (4) http://nathanleclaire.com/blog/2014/04/19/5-angularjs-antipatterns-and-pitfalls/).

Malhar dashboard directive itself creates a child scope prototypically inherits parent scope from your app. Since angular supports selectively binding of parent scope properties within an isolate scope as per, say http://www.sitepoint.com/practical-guide-angularjs-directives-part-two/, you should be able to pull in other specific properties from your app one by one.

**Comment by robertmazzo** [comment]
It sounds like you need to add a new Widget Definition, and hook up the `dataModelType` to a new data model.
Please refere to base class in factory `'WidgetDataModel'` .

example: getting test data for a Kendo UI treelist

   {                
                name: myWidgetEnum.TREELIST,   //'chart_treelist',
                title: 'Tree Grid',
                active: true,           // added on 4/14/2015 BM:
                editingTitle: true,     // seems to make no diff here; see $scope.editTitle function in DashboardWidgetCtrl
                size: size,
                fixedSize: fixedSize,   // 04/28/2015 BM:
                templateUrl: 'app/shared/gadget-templates/tree-list.html',
                dataAttrName: 'treeListOptions',
                dataModelType: TreeListDataModel,
                dataModelOptions: {},               // this property will be persisted in DashboardState factory
                initImage: 'images2/table.png',
                gadgetConfigured: false,   // false hides the widget-content div in dashboard
                gadgetType: 'table',
                chartType: 'treelist',
                settingsModalOptions: { // see 'MainCtrl' controller
                }                
            },

FACTORY CODE:

  'use strict';

   angular.module('myModeul')
    .factory('TreeListDataModel', function (WidgetDataModel, gadgetInitService) {
      function TreeListDataModel() {
      }
      TreeListDataModel.prototype = Object.create(WidgetDataModel.prototype);
      TreeListDataModel.prototype.constructor = WidgetDataModel;

      angular.extend(TreeListDataModel.prototype, {
          init: function () {                            
            
              this.treeListOptions = gadgetInitService.initTreeList2();
              this.treeListOptions.height = 300;     
              this.updateScope(this.treeListOptions);  // see WidgetDataModel factory    
          },
          updateScope: function (data) {              
              this.widgetScope.treeListOptions = data;
              this.dataModelOptions = data;
          },          
          destroy: function () {
              WidgetDataModel.prototype.destroy.call(this);
          }
      });

      return TreeListDataModel;
  });

**Comment by wvary** [comment]
@spiermar I beieve awashbrook and robertmazzo have answered your question regarding directive.  Simply put, when creating directives, we can either create a new scope (isolated scope) or inherit the parent scope.  Each use case has it's pros and cons.  Because the widget directive is designed to render multiple widgets on a single page, it makes sense that the developer chose the isolated scope method.

Also, the sample statements you provided in your question have totally different meanings

```
scope: {
    data: '='
}
```

The statement above tells AngularJS to create a directive with a new isolated scope.  In this new scope, there should be a property named data.

```
link: function (scope) {
    scope.data = '=';
}
```

The statement above simple says assign the literal string containing the equal sign to the property named data in the scope.  Here the scope can be isolated or inherited because we don't have the complete statement.

The two statements below are just to demonstrate the difference, I'm not suggesting either method because I am not familiar with your application.

**Isolated Scope:**

```
directives.directive('lineTimeSeries', function (D3Service) {
    return {
        restrict: 'A',
        replace: true,
        templateUrl: 'partials/line-timeseries.html',
        scope: {                            // this section indicates new
            data: '='                       //  isolated scope will be created  
        },                                  // when the directive is created
        link: function (scope) {
            scope.yAxisTickFormat = D3Service.yAxisTickFormat;
            scope.xAxisTickFormat = D3Service.xAxisTickFormat;
            scope.yFunction = D3Service.yFunction;
            scope.xFunction = D3Service.xFunction;
        }
    };
});
```

**Inherited Scope:**

```
directives.directive('lineTimeSeries', function (D3Service) {
    return {
        restrict: 'A',
        replace: true,
        templateUrl: 'partials/line-timeseries.html',
        link: function (scope) {
            scope.yAxisTickFormat = D3Service.yAxisTickFormat;
            scope.xAxisTickFormat = D3Service.xAxisTickFormat;
            scope.yFunction = D3Service.yFunction;
            scope.xFunction = D3Service.xFunction;
        }
    };
});

```

**Comment by spiermar** [comment]
Yes, that was resolved. Thank you @wvary !
